version: 2

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    working_directory: ~/code

    steps:
      - checkout
      - run: ./build.sh
      - persist_to_workspace:
          root: .
          paths:
            - build
  
  use-output:
    docker: 
      - image: cimg/base:2020.01
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run: 
          command: |
            ls /tmp/workspace/build
            cat /tmp/workspace/build/output.txt

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: 
                - master
                - test-filter
      - use-output:
          requires:
            - build
